### ISSUE TITLE
Click progress to special piece problem

### ISSUE THREAD

**Issue by whitersun** [Yizack/nuxt-musicfyplayer#3]
Environment:
- "nuxt": "^3.13.0"
- "nuxt-musicfyplayer": "^2.0.2"

Runtime: pnpm

Bug description:
when I played the music that make progress bar start to play, but when I clicked to special place I want in progress bar to skip, I got return to init was played song. When I try your dropbox that work ok, but when using src will make this problem appearing.

my demo link:
https://stackblitz.com/edit/nuxt-starter-rxvzjm

**Comment by Yizack** [comment]
Hey! @whitersun! at first look, I could notice a few things in your demo link that could be causing the issue

1. The audio file used in your demo, even if it has the `.mp3` file extension, is being served as a `mp4` video, this could be causing the issue.
![image](https://github.com/user-attachments/assets/f81675af-a3c7-4c30-9524-9c892b27ab8f)
2. Another possibility that could be causing the problem is that the host serving the file is not accepting ranges of bytes or streaming/actions due to missing or unset headers.
3. I tried downloading the audio to see if it could be the server but it's being downloaded as mp4 too.
![image](https://github.com/user-attachments/assets/eacbbd5b-ff76-4acd-9066-97689b275794)
4. The progress bar click to rewind/fast forward in the original source doesn't work either.
5. I have tested with other mp3 sources instead of dropbox and it works properly!

I'm not sure I have a solution for this right now, or if it's even possible to fix the audio controls for files with the wrong content type or headers 😢

**Comment by whitersun** [comment]
Thank you, Yizick, for addressing the issue I was facing. At the time, I was confused, unsure whether it was an error or a problem with the music link. However, after your explanation regarding the Content-Type, I checked the Content-Type of the music link I sent in Stackblitz. Upon inspection, I found that the Content-Type was audio/mpeg and not video/mp4. Besides the Content-Type, is there anything else I should be mindful of?
Apologies if the question above seems too naive; I'm not actually an expert in the audio, mp3 field.

![image](https://github.com/user-attachments/assets/c5699644-62ea-4b7f-9cc5-e05865bd77d1)

**Comment by Yizack** [comment]
@whitersun hello again! okay I have come up with some ideas

First question, are you the owner or do you have development access to https://learn-enery-quiz.zeabur.app?
if the answer is YES, let's give this a try, add the following in its `nuxt.config.ts` file

```js
export default defineNuxtConfig({
  routeRules: {
    "/upload/audio/**": { headers: { "Accept-Ranges": "bytes" } },
  },
})
```

This will ensure all audio files have the `Accept-Ranges: bytes` header, allowing HTML to control the audio bar positioning. Just to let you know, setting headers doesn't work for static files in dev mode at the moment due to a Nuxt bug, but it works in production build. I also recommend clearing the browser cache after this change has been deployed!

If the answer to the first question is NO, and you are only making use of their resources, what you could do to force it to work is create a server API route in your project that fetches the audio files so it works as a proxy and set the `Accept-Ranges: bytes` header in your server API response, I can try to assist you doing this part if you want :)

**Comment by whitersun** [comment]
Thank you Yizack, I will try it. Seem like this issue not truthly cause of your lib, so I will close it, by the way is good to have your help. Thank you very much ~
